type: steep.trainer.PyGTrainer

args:
  train_ratio: 0.8
  val_ratio: 0.1
  split_type: random
  spatial_block_grid_size: 4
  epochs: 1
  shuffle: true
  batchsize: 2
  device: cpu
  grad_norm_clip: 1.0
  accelerator: auto
  devices: 1
  strategy: auto
  precision: 32-true
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  enable_progress_bar: true
  enable_model_summary: false
  num_sanity_val_steps: 0
  num_workers: 0
  persistent_workers:
  pin_memory:
  run_wandb: false
