type: steep.benchmark.Benchmark

args:
  label_keys: [class, subclass, supertype, cluster]
  num_workers: 1
  random_seed: 0
  n_neighbors: 15
  leiden_resolution: 1.0
  clustering_backend: rapids
  resume_from_checkpoint: true
  run_wandb: false
